# Generated by Django 6.0.1 on 2026-02-04 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='default.png', upload_to='profile_pics/')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_image', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Not Paid', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.contributiontype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin aliyethibitisha malipo haya', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_paid'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_number__isnull', False)), fields=('reference_number',), name='unique_reference_number')],
            },
        ),
    ]
